language: cpp
compiler: gcc

os: linux
dist: xenial
sudo: required

addons:
  apt:
    sources:
      - sourceline: 'ppa:duggan/bats'
    packages:
      - git
      - gcc-mipsel-linux-gnu
      - bats # Unit testing in Bash

before_install:
  - sudo bash README.Debian

script:
  - echo travis_fold:start:Compilation
  - cd code
  - make
  - echo travis_fold:end:Compilation
  - cd build
  - bats -p ../test/test_all.bats