language: cpp
compiler: gcc

os: linux
dist: xenial
sudo: required

addons:
  apt:
    packages:
      - gcc-mipsel-linux-gnu

before_install:
  - sudo bash README.Debian

script:
  - cd code
  - make