language: cpp
compiler: gcc

os: linux
dist: xenial
sudo: required

addons:
  apt:
    sources:
      - sourceline: 'ppa:duggan/bats'
    packages:
      - git
      - gcc-mipsel-linux-gnu
      - bats # Unit testing in Bash

before_install:
  - sudo bash README.Debian

script:
  - echo "[0K[33;1mCompilation[0m" && echo -en 'travis_fold:start:compilation\\r'
  - cd code
  - make
  - echo -en 'travis_fold:end:compilation\\r'
  - cd build
  - bats ../test/test_all.bats